# Generated by Django 4.2.4 on 2023-08-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_ref',
            field=models.CharField(default='sKJAPk', editable=False, max_length=6, unique=True, verbose_name='Porsonal reference'),
        ),
    ]
