# Generated by Django 4.2.4 on 2023-08-08 05:17

import backend.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_user_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_ref',
            field=models.CharField(default='Ppvmzf', editable=False, max_length=6, unique=True, verbose_name='Porsonal reference'),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(default='5384', editable=False, max_length=6, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', backend.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('child_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child', to=settings.AUTH_USER_MODEL)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
