# Generated by Django 4.2.4 on 2023-08-09 16:17

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_user_ref_token_referal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsKey',
            fields=[
                ('phone', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('key', models.CharField(default=users.models.CodeGenerator.get_nums(4), editable=False, max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_ref',
            field=models.CharField(default=users.models.CodeGenerator.get_chars(6), editable=False, max_length=6, unique=True, verbose_name='Porsonal reference'),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
