# Generated by Django 4.2.4 on 2023-08-12 07:57

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_smskey_alter_user_user_ref_delete_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SmsKey',
            new_name='SmsCode',
        ),
        migrations.RenameField(
            model_name='smscode',
            old_name='key',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_ref',
            field=models.CharField(default=users.models.CodeGenerator.get_chars(6), editable=False, max_length=6, unique=True, verbose_name='Personal reference'),
        ),
    ]
