# Generated by Django 4.2.4 on 2023-08-12 21:32

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_smscode_code_alter_user_user_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='code',
            field=models.CharField(default=users.models.CodeGenerator.get_nums, editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(editable=False, max_length=12, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_ref',
            field=models.CharField(default=users.models.CodeGenerator.get_chars, editable=False, max_length=6, unique=True, verbose_name='Personal reference'),
        ),
    ]
